import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { SWRConfig } from 'swr'
import styles from '../styles/Home.module.css'
import FR from './FR'

export default function home(){
  return (
    <div className={styles.container}>
      <Head>
        <title>Binance Futures FundingRate table</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
          <FR />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://y.at/☯️👌🤔💻☯️"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by {'@tofu4956'} 2021
        </a>
      </footer>
    </div>
  )
}